### ISSUE TITLE
IndexError: index 8821 is out of bounds for axis 0 with size 8813

### ISSUE THREAD

**Issue by inmarelibero** [lucaspetry/news-similarity#1]
Hi @lucaspetry  I have a weird error while running `python3 exp_replication.py`:
```
...
Computing replication for technique NEL ...
Computing/loading distances for technique NEL ...
Computing/loading distances for technique NEL ... DONE!
Traceback (most recent call last):
  File "exp_replication.py", line 172, in <module>
    replication, obs = get_replication(news, sim_matrix, threshold)
  File "exp_replication.py", line 37, in get_replication
    if sim_matrix[idx][idx2] >= threshold:
IndexError: index 8821 is out of bounds for axis 0 with size 8813
```

I just imported `data/database_postgres_binary.backup` with pgAdmin4, and then run `python3 exp_replication.py`

what can it be?

**Comment by lucaspetry** [comment]
Hi @inmarelibero,

I think that maybe the files with the cached vectors here may be outdated (files 'data/vectors_*.bin'). I checked 'data/vectors_nel.bin' and it contains 8813 entries, so I'm assuming in the database we have 8821 entries and that's why you got the error. So could you try removing these files and running the script again? It will take longer because it will compute the vectors again.

Please let me know if that works.

**Comment by inmarelibero** [comment]
thanks for the answer @lucaspetry 

I tried deleting:
- vectors_doc2vec.bin
- vectors_doc2vec.bin.trainables.syn1neg.npy
- vectors_doc2vec.bin.wv.vectors.npy
-vectors_nel.bin

then run the script again, waited long time, but the error is still the same

**Comment by inmarelibero** [comment]
@lucaspetry any suggestion?

**Comment by lucaspetry** [comment]
Hi @inmarelibero,

I finally had some time to test it out. So I cloned the repo, created the database from the binary backup, setup all the packages, and did not get the error you're having.
The only reason I can think of is that you have incompatible vectors_nel.bin and dist_nel.bin files in the data folder. If you delete both of them and run the script again, it should work.
